# Generated by Django 3.1.7 on 2021-07-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop_form',
            name='slug',
            field=models.CharField(default='SLUG', max_length=100),
        ),
    ]
