# Generated by Django 3.1.7 on 2021-07-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshop_form_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=70, verbose_name='Email')),
                ('wa_number', models.CharField(max_length=15, verbose_name='WhatsApp Number')),
                ('ph_number', models.CharField(max_length=15, verbose_name='Calling Number')),
                ('intro', models.CharField(max_length=700, verbose_name='Student Intro')),
                ('tag', models.CharField(max_length=100, verbose_name='Tag')),
            ],
        ),
    ]
